//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AZS
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdersFromClient
    {
        public int IdOrder { get; set; }
        public int IdUser { get; set; }
        public int IdPetrol { get; set; }
        public int CountPetrol { get; set; }
        public int IdGasStation { get; set; }
    
        public virtual GasStation GasStation { get; set; }
        public virtual Petrol Petrol { get; set; }
        public virtual User User { get; set; }
    }
}
